name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (versões compatíveis entre si)
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.0.0
  firebase_database: ^11.0.0

  # UI e utilitários
  google_fonts: ^6.2.1
  provider: ^6.1.4
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  share_plus: ^7.2.2
  image_picker: ^1.1.0
  google_sign_in: ^6.3.0
  font_awesome_flutter: ^10.8.0

  transparent_image: ^2.0.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  diacritic: ^0.1.6
  qr_flutter: ^4.0.0
  clipboard: ^0.1.3

  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/logolm.jpg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  android: true
  image_path: "/assets/icon/logoml.jpg"
